"""empty message

Revision ID: 09fdcda52f9b
Revises: 9ae975fa7525
Create Date: 2023-12-25 11:48:59.024500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09fdcda52f9b'
down_revision = '9ae975fa7525'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('policies_accepted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('policies_accepted')

    # ### end Alembic commands ###
