"""empty message

Revision ID: 277d79465eb8
Revises: 848fea3a2709
Create Date: 2023-12-15 23:28:18.309809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '277d79465eb8'
down_revision = '848fea3a2709'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.drop_column('slug')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
