"""empty message

Revision ID: 372aeb595109
Revises: 47e1a0a9e8a2
Create Date: 2023-11-05 15:04:36.749219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '372aeb595109'
down_revision = '47e1a0a9e8a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.drop_column('date_created')

    # ### end Alembic commands ###
