"""empty message

Revision ID: 4a4cb9d1b1c7
Revises: 948c9af69650
Create Date: 2023-12-14 00:24:35.258465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a4cb9d1b1c7'
down_revision = '948c9af69650'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quota', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package', schema=None) as batch_op:
        batch_op.drop_column('quota')

    # ### end Alembic commands ###
