"""empty message

Revision ID: 719abc357643
Revises: 928f9bc5b4b8
Create Date: 2023-12-19 04:00:45.010543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '719abc357643'
down_revision = '928f9bc5b4b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article')
    # ### end Alembic commands ###
