"""empty message

Revision ID: 848fea3a2709
Revises: 4a4cb9d1b1c7
Create Date: 2023-12-15 23:26:50.691588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '848fea3a2709'
down_revision = '4a4cb9d1b1c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
