"""empty message

Revision ID: 8642a94f7df7
Revises: a374bcce93ef
Create Date: 2023-11-25 20:49:24.981382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8642a94f7df7'
down_revision = 'a374bcce93ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.drop_column('coupon_offer')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coupon_offer', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
