"""empty message

Revision ID: 928f9bc5b4b8
Revises: 277d79465eb8
Create Date: 2023-12-18 01:17:32.638492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '928f9bc5b4b8'
down_revision = '277d79465eb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('package')
    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.add_column(sa.Column('package', sa.String(), nullable=True))
        batch_op.drop_column('package_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.add_column(sa.Column('package_id', sa.INTEGER(), nullable=True))
        batch_op.drop_column('package')

    op.create_table('package',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('unlimited', sa.BOOLEAN(), nullable=True),
    sa.Column('quota', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
