"""empty message

Revision ID: 948c9af69650
Revises: 33ca9552f568
Create Date: 2023-12-14 00:24:17.214790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '948c9af69650'
down_revision = '33ca9552f568'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package', schema=None) as batch_op:
        batch_op.drop_column('quota_custom_campaign')
        batch_op.drop_column('quota_general_campaign')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quota_general_campaign', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('quota_custom_campaign', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
