"""empty message

Revision ID: a374bcce93ef
Revises: dbbad29ddf41
Create Date: 2023-11-25 20:48:18.791254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a374bcce93ef'
down_revision = 'dbbad29ddf41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coupon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('offer', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('redeemed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coupon', schema=None) as batch_op:
        batch_op.drop_column('redeemed')
        batch_op.drop_column('offer')

    # ### end Alembic commands ###
