"""empty message

Revision ID: e0bef6e34633
Revises: 719abc357643
Create Date: 2023-12-21 03:19:28.350077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0bef6e34633'
down_revision = '719abc357643'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.drop_column('state')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.VARCHAR(length=10), nullable=True))

    # ### end Alembic commands ###
