"""empty message

Revision ID: e96da2c24076
Revises: e48bb551c706
Create Date: 2023-12-13 23:45:40.509492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e96da2c24076'
down_revision = 'e48bb551c706'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('package',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('quota_custom_campaign', sa.Integer(), nullable=True),
    sa.Column('quota_general_campaign', sa.Integer(), nullable=True),
    sa.Column('unlimited', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=10), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('state')
        batch_op.drop_column('role')

    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.drop_column('state')
        batch_op.drop_column('category')

    op.drop_table('package')
    # ### end Alembic commands ###
