"""empty message

Revision ID: f006eef49cf2
Revises: b2c3b494406b
Create Date: 2024-01-08 10:14:01.014365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f006eef49cf2'
down_revision = 'b2c3b494406b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coupons_generated', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('coupons_redeemed', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.drop_column('coupons_redeemed')
        batch_op.drop_column('coupons_generated')

    # ### end Alembic commands ###
