"""empty message

Revision ID: f8d3b6c5c756
Revises: d4e9b45fe098
Create Date: 2023-12-21 04:03:31.832544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8d3b6c5c756'
down_revision = 'd4e9b45fe098'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action', schema=None) as batch_op:
        batch_op.drop_column('date_created')

    # ### end Alembic commands ###
